In [7]:
import numpy as np

In [3]:
lst=[[1,2,3],[3,4,5],[6,7,8]]
x = np.array(lst)
x

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
x.ndim

2

In [4]:
x.reshape

<function ndarray.reshape>

In [5]:
x.shape

(3, 3)

In [12]:
x.shape

(3, 3)

In [8]:
x=[[1,2,3],[4,5,6],[4,3,5],[2,5,6]]
x.ndim

AttributeError: 'list' object has no attribute 'ndim'

In [17]:
x=np.random.randint(10,100,15).reshape(3,5)
x

array([[95, 63, 30, 34, 73],
       [31, 52, 35, 78, 61],
       [98, 43, 79, 28, 68]])

In [21]:
x=np.random.randint(1,100,50).reshape(2,25)
x

array([[54, 84, 82, 38,  7, 28, 19, 89, 34, 56, 98, 66, 59, 59, 67, 56,
        25, 99, 13, 19, 70, 22, 44, 58, 30],
       [60, 77, 20, 66, 52, 81, 21,  7, 35, 66, 34, 18,  2, 39, 31, 14,
        96, 49, 64, 95, 24, 34, 11,  3, 84]])

In [23]:
lst = [[[10,20,30],[20,40,20],[20,50,20]]]
x=np.array(lst)
x

array([[[10, 20, 30],
        [20, 40, 20],
        [20, 50, 20]]])

In [24]:
x.ndim

3

In [25]:
x.shape

(1, 3, 3)

In [28]:
x.reshape(9,1)

array([[10],
       [20],
       [30],
       [20],
       [40],
       [20],
       [20],
       [50],
       [20]])

In [33]:
lst= [[[10,20,30],[20,40,20],[20,50,20],[20,20,10]]]
lst

[[[10, 20, 30], [20, 40, 20], [20, 50, 20], [20, 20, 10]]]

In [34]:
x=np.array(lst)
x

array([[[10, 20, 30],
        [20, 40, 20],
        [20, 50, 20],
        [20, 20, 10]]])

In [36]:
lst=[[[10,20],[12,34],[90,10],[12,14]],[[20,54],[50,23],[40,20],[20,50]]]
lst

[[[10, 20], [12, 34], [90, 10], [12, 14]],
 [[20, 54], [50, 23], [40, 20], [20, 50]]]

In [37]:
x=np.array(lst)

In [38]:
x

array([[[10, 20],
        [12, 34],
        [90, 10],
        [12, 14]],

       [[20, 54],
        [50, 23],
        [40, 20],
        [20, 50]]])

In [43]:
x.reshape(2,2,4)

array([[[10, 20, 12, 34],
        [90, 10, 12, 14]],

       [[20, 54, 50, 23],
        [40, 20, 20, 50]]])

In [45]:
lst=[[[1,2],[2,4],[4,1],[5,9]],[[2,7],[2,6],[2,5],[4,5]],[[5,0],[2,6],[2,9],[4,2]]]
x= np.array(lst)
x

array([[[1, 2],
        [2, 4],
        [4, 1],
        [5, 9]],

       [[2, 7],
        [2, 6],
        [2, 5],
        [4, 5]],

       [[5, 0],
        [2, 6],
        [2, 9],
        [4, 2]]])

In [46]:
x.ndim

3

In [47]:
x=np.random.randint(10,100,60).reshape(3,4,5)
x

array([[[16, 88, 19, 63, 91],
        [48, 43, 28, 58, 81],
        [78, 63, 64, 35, 33],
        [98, 99, 51, 67, 93]],

       [[24, 86, 88, 14, 55],
        [25, 82, 92, 50, 48],
        [32, 58, 87, 70, 36],
        [85, 61, 75, 54, 67]],

       [[51, 28, 40, 14, 78],
        [78, 71, 92, 57, 63],
        [86, 58, 53, 70, 78],
        [56, 29, 46, 95, 34]]])

In [48]:
x=np.array([10,20,30,40,50,60])
x[-1]

60

In [52]:
x[2:5:]

array([30, 40, 50])

In [53]:
np.random.seed(127)
x=np.random.randint(10,100,15).reshape(3,5)
x

array([[83, 70, 46, 77, 39],
       [37, 19, 65, 33, 49],
       [99, 59, 29, 28, 66]])

In [54]:
x[-3]

array([83, 70, 46, 77, 39])

In [55]:
x[0:2:1]

array([[83, 70, 46, 77, 39],
       [37, 19, 65, 33, 49]])

In [56]:
x[2:3:]

array([[99, 59, 29, 28, 66]])

In [60]:
x[2:1:]

array([], shape=(0, 5), dtype=int32)

In [70]:
a=np.arange(3*3*3).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [89]:
a[1:2, 0:2, 1:2]

array([[[10],
        [13]]])

In [93]:
a[1:2,1:2,1:3]

array([[[13, 14]]])

In [95]:
x=np.array([10,20,30,40,50,60,70,80,90])
x

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [96]:
np.sum(x)

450

In [97]:
np.min(x)

10

In [98]:
np.max(x)

90